####################################################################################################
# Helm chart values for the redeployments of the Curity Token Handler with an existing configuration
####################################################################################################
replicaCount: 2
fullnameOverride: tokenhandler

image:
  repository: custom_tokenhandler
  tag: '1.0.0'

curity:
  adminUiHttp: true
  admin:
    serviceAccount:
      name: curity-tokenhandler-admin
    logging:
      level: INFO

  runtime:
    serviceAccount:
      name: curity-tokenhandler-runtime
    logging:
      level: INFO
      #image: 'busybox:latest'
      #stdout: true
      #logs:
      #- request
      #- audit

  config:
    uiEnabled: true
    environmentVariableConfigMaps:
    - idsvr-parameters
    environmentVariableSecrets:
    - idsvr-protected-parameters

networkpolicy:
  enabled: true
  apigatewayNamespace: 'apigateway'
